export const ADD_FEED_REQUEST = "ADD_FEED_REQUEST";
export const ADD_FEED_SUCCESS = "ADD_FEED_SUCCESS";
export const ADD_FEED_ERROR = "ADD_FEED_ERROR";

export const GET_FEED_REQUEST = "GET_FEED_REQUEST";
export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS";
export const GET_FEED_ERROR = "GET_FEED_ERROR";

export const GET_RECENT_CHAT_REQUEST = "GET_RECENT_CHAT_REQUEST";
export const GET_RECENT_CHAT_SUCCESS = "GET_RECENT_CHAT_SUCCESS";
export const GET_RECENT_CHAT_ERROR = "GET_RECENT_CHAT_ERROR";

export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_ERROR = "GET_CHAT_ERROR";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const SAVE_DOCUMENT_REQUEST = "SAVE_DOCUMENT_REQUEST";
export const SAVE_DOCUMENT_SUCCESS = "SAVE_DOCUMENT_SUCCESS";
export const SAVE_DOCUMENT_ERROR = "SAVE_DOCUMENT_ERROR";
export const CLEAR_SAVE_DOCUMENT_REQUEST = "CLEAR_SAVE_DOCUMENT_REQUEST";

export const FEED_LIKE_UNLIKE_REQUEST = "FEED_LIKE_UNLIKE_REQUEST";
export const FEED_LIKE_UNLIKE_SUCCESS = "FEED_LIKE_UNLIKE_SUCCESS";
export const FEED_LIKE_UNLIKE_ERROR = "FEED_LIKE_UNLIKE_ERROR";
